scheduleapi/forms/useractions.py
# -*- coding: utf-8 -*-

from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import Required, Optional, Length, Email, EqualTo


class Login(Form):
    username = StringField('Username', validators=[
        Required(message='Please type your username')
    ])
    password = PasswordField('Password', validators=[
        Required(message='Please type your password')
    ])
    remember_me = BooleanField('Remember me?', default=False)


class Register(Form):
    username = StringField('Username', validators=[
        Required(message='Please pick a username'),
        Length(min=2, max=25,
               message='Username needs to be between 2 and 25 characters'
               )
    ])
    password = PasswordField('Password', validators=[
        Required(message='Please pick a password'),
        Length(min=5, max=50,
               message='Password needs to be between 5 and 50 characters'
               ),
        EqualTo('pwd_confirm', message='Passwords must match')
    ])
    pwd_confirm = PasswordField('Repeat password')
    email = StringField('Email', validators=[
        Optional(),
        Email(message='Email is not valid')
    ])


class UserSettings(Register):
    password = PasswordField('Password', validators=[
        Optional(),
        Length(min=5, max=50,
               message='Password needs to be between 5 and 50 characters'
               ),
        EqualTo('pwd_confirm', message='Passwords must match')
    ])
    pwd_confirm = PasswordField('Repeat password')
    email = StringField('Email', validators=[
        Optional(),
        Email(message='Email is not valid')
    ])

scheduleapi/views/generic.py
# -*- coding: utf-8 -*-

from flask import (
    Blueprint, render_template, abort, flash, session, request,
    redirect, url_for
)
from flask.ext.login import login_required, current_user
from jinja2 import TemplateNotFound

from ..database.models import Apikey
from ..forms.useractions import UserSettings as UserSettingsForm
from ..controllers.database import get_session
from ..controllers.users import generate_apikey, fetch_apikeys, remove_apikey


bp = Blueprint('generic', __name__)


@bp.route('/')
def serve_frontpage():
    try:
        return render_template('index.html')
    except TemplateNotFound:
        abort(404)


@bp.route('/about')
def serve_aboutpage():
    try:
        return render_template('about.html')
    except TemplateNotFound:
        abort(404)


@bp.route('/ping')
def serve_pong():
    return "PONG", 200


@bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings_yo():
    form = UserSettingsForm(request.form)
    if request.method == 'POST' and form.validate():
        if save_settings(form):
            pass
    try:
        return render_template('forms/settings.html', form=form)
    except TemplateNotFound:
        abort(404)


@bp.route('/settings/apikeys', methods=['GET'])
@login_required
def get_apikeys():
    try:
        return render_template('forms/apikeys.html', apikeys=fetch_apikeys(user=current_user))
    except TemplateNotFound:
        abort(404)


@bp.route('/settings/apikeys/new', methods=['GET'])
@login_required
def new_apikey():
    api_key = generate_apikey(user=current_user)
    return redirect(url_for('generic.get_apikeys'))


@bp.route('/settings/apikeys/<id>/delete', methods=['GET'])
@bp.route('/settings/apikeys/<id>', methods=['DELETE'])
@login_required
def del_apikey(id):
    session = get_session()
    apikey = session.query(Apikey).filter(
        Apikey.user_id == current_user.id).filter(Apikey.id == id).first()
    if remove_apikey(apikey):
        flash("API key was removed")
    else:
        flash("API key could not be removed")

    return redirect(url_for('generic.get_apikeys'))

scheduleapi/views/useractions.py
# -*- coding: utf-8 -*-

import flask
from flask import (
    Blueprint, render_template, abort, flash, session, request,
    redirect, url_for
)
from flask.ext.login import login_user, logout_user, login_required
from jinja2 import TemplateNotFound

from ..forms.useractions import Login as LoginForm, Register as RegisterForm
from ..controllers.users import register as do_register, encrypt_password, check_password
from ..controllers.database import get_session
from ..database.models import User


bp = Blueprint('useractions', __name__, url_prefix='/usr')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        session = get_session()
        user = session.query(User).filter(
            User.username == form.username.data).first()
        if user:
            if check_password(form.password.data, user.password):
                user.authenticated = True
                session.add(user)
                session.commit()
                login_user(user, remember=form.remember_me.data)
                return redirect(url_for('generic.serve_frontpage'))
        else:
            flash("Invalid credentials!")
    try:
        return render_template('forms/login.html', form=form)
    except TemplateNotFound:
        abort(404)

# Matte finns inte


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        if do_register(form.data['username'], form.data['password'], form.data['email']):
            flash("Registered successfully. You may now login")
            return redirect(url_for('useractions.login'))
        else:
            flash("Username already taken!")
    try:
        return render_template('forms/register.html', form=form)
    except TemplateNotFound:
        abort(404)


@bp.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('generic.serve_frontpage'))

scheduleapi/templates/_formhelpers.html
{% macro render_field(field) %}
  {% if field.errors %}
  <div class="form-group has-error">
  {% else %}
  <div class="form-group">
  {% endif %}
    {{ field.label(class="col-sm-2 control-label") }}
    <div class="col-sm-10">
      {{ field(class='form-control')|safe }}
    </div>
  </div>
  {% if field.errors %}
    {% for error in field.errors %}
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{{ error }}
      </div>
    {% endfor %}
  {% endif %}
{% endmacro %}

scheduleapi/templates/about.html
{% extends "layout.html" %}
{% block title %}About ScheduleAPI{% endblock %}

{% block content %}
<div class="container">
  <div class="jumbotron">
    <h1>What can I do for you?</h1>
    <hr>
  </div>
</div>
{% endblock %}

scheduleapi/templates/index.html
{% extends "layout.html" %}
{% block title %}ScheduleAPI{% endblock %}

{% block content %}
<div class="container">
  <div class="jumbotron container">
    <h1>Your new calendar</h1>
    <hr>
    <!-- Random inspirational quotes -->
    <blockquote>
      <p class="lead">The key is not to prioritize what's on your schedule, but to schedule your priorities.</p>
      <footer>Stephen Covey</footer>
    </blockquote>
    <blockquote class="blockquote-reverse">
      <p class="lead">And in the end it's not the years in your life that count. It's the life in your years.</p>
      <footer>Abraham Lincoln </footer>
    </blockquote>
    <blockquote>
      <p class="lead">Life is what happens when you are busy making other plans.</p>
      <footer>John Lennon</footer>
    </blockquote>
  </div>
</div>
{% endblock %}

scheduleapi/templates/layout.html
{% extends "bootstrap/base.html" %}

{% block html_attribs %} lang="en"{% endblock %}

{% block navbar %}
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{url_for('generic.serve_frontpage')}}">Schedule API</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{{url_for('generic.serve_frontpage')}}">Home</a></li>
        <li><a href="{{url_for('generic.serve_aboutpage')}}">About</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Help <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="https://github.com/phille97/scheduleapi-server/blob/master/api_doc.md">API Documentation <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span></a></li> 
            <li><a href="https://github.com/phille97/scheduleapi-server/issues">Support <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span></a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li><a class="disabled" href="#">Welcome <b>{{ current_user.username }}</b></a></li>
        <li><a href="{{url_for('generic.settings_yo')}}">Settings</a></li> 
        <li><a href="{{url_for('useractions.logout')}}">Logout</a></li> 
        {% else %}
        <li><a href="{{url_for('useractions.login')}}">Login</a></li> 
        <li><a href="{{url_for('useractions.register')}}">Register</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>
{% with messages = get_flashed_messages() %}
  {% if messages %}
    <div class="container" id="aspnetForm">
    {% for message in messages %}
      <div class="container alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ message }}
      </div>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}
{% endblock %}

{% block styles %}
{{super()}}
<link rel="stylesheet"
      href="{{url_for('static', filename='css/main.min.css')}}">
{% endblock %}

{% block scripts %}
{{super()}}
<script src="{{url_for('static', filename='js/main.min.js')}}"></script>
{% endblock %}