scheduleapi/forms/useractions.py
# -*- coding: utf-8 -*-

from flask_wtf import Form
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import Required, Optional, Length, Email, EqualTo


class Login(Form):
    username = StringField('Username', validators=[
        Required(message='Please type your username')
    ])
    password = PasswordField('Password', validators=[
        Required(message='Please type your password')
    ])
    remember_me = BooleanField('Remember me?', default=False)


class Register(Form):
    username = StringField('Username', validators=[
        Required(message='Please pick a username'),
        Length(min=2, max=25,
               message='Username needs to be between 2 and 25 characters'
               )
    ])
    password = PasswordField('Password', validators=[
        Required(message='Please pick a password'),
        Length(min=5, max=50,
               message='Password needs to be between 5 and 50 characters'
               ),
        EqualTo('pwd_confirm', message='Passwords must match')
    ])
    pwd_confirm = PasswordField('Repeat password')
    email = StringField('Email', validators=[
        Optional(),
        Email(message='Email is not valid')
    ])


class UserSettings(Register):
    password = PasswordField('Password', validators=[
        Optional(),
        Length(min=5, max=50,
               message='Password needs to be between 5 and 50 characters'
               ),
        EqualTo('pwd_confirm', message='Passwords must match')
    ])
    pwd_confirm = PasswordField('Repeat password')
    email = StringField('Email', validators=[
        Optional(),
        Email(message='Email is not valid')
    ])

scheduleapi/views/generic.py
# -*- coding: utf-8 -*-

from flask import (
    Blueprint, render_template, abort, flash, session, request,
    redirect, url_for
)
from flask.ext.login import login_required, current_user
from jinja2 import TemplateNotFound

from ..database.models import Apikey
from ..forms.useractions import UserSettings as UserSettingsForm
from ..controllers.database import get_session
from ..controllers.users import generate_apikey, fetch_apikeys, remove_apikey


bp = Blueprint('generic', __name__)


@bp.route('/')
def serve_frontpage():
    try:
        return render_template('index.html')
    except TemplateNotFound:
        abort(404)


@bp.route('/about')
def serve_aboutpage():
    try:
        return render_template('about.html')
    except TemplateNotFound:
        abort(404)


@bp.route('/ping')
def serve_pong():
    return "PONG", 200


@bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings_yo():
    form = UserSettingsForm(request.form)
    if request.method == 'POST' and form.validate():
        if save_settings(form):
            pass
    try:
        return render_template('forms/settings.html', form=form)
    except TemplateNotFound:
        abort(404)


@bp.route('/settings/apikeys', methods=['GET'])
@login_required
def get_apikeys():
    try:
        return render_template('forms/apikeys.html', apikeys=fetch_apikeys(user=current_user))
    except TemplateNotFound:
        abort(404)


@bp.route('/settings/apikeys/new', methods=['GET'])
@login_required
def new_apikey():
    api_key = generate_apikey(user=current_user)
    return redirect(url_for('generic.get_apikeys'))


@bp.route('/settings/apikeys/<id>/delete', methods=['GET'])
@bp.route('/settings/apikeys/<id>', methods=['DELETE'])
@login_required
def del_apikey(id):
    session = get_session()
    apikey = session.query(Apikey).filter(
        Apikey.user_id == current_user.id).filter(Apikey.id == id).first()
    if remove_apikey(apikey):
        flash("API key was removed")
    else:
        flash("API key could not be removed")

    return redirect(url_for('generic.get_apikeys'))

scheduleapi/views/useractions.py
# -*- coding: utf-8 -*-

import flask
from flask import (
    Blueprint, render_template, abort, flash, session, request,
    redirect, url_for
)
from flask.ext.login import login_user, logout_user, login_required
from jinja2 import TemplateNotFound

from ..forms.useractions import Login as LoginForm, Register as RegisterForm
from ..controllers.users import register as do_register, encrypt_password, check_password
from ..controllers.database import get_session
from ..database.models import User


bp = Blueprint('useractions', __name__, url_prefix='/usr')


@bp.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        session = get_session()
        user = session.query(User).filter(
            User.username == form.username.data).first()
        if user:
            if check_password(form.password.data, user.password):
                user.authenticated = True
                session.add(user)
                session.commit()
                login_user(user, remember=form.remember_me.data)
                return redirect(url_for('generic.serve_frontpage'))
        else:
            flash("Invalid credentials!")
    try:
        return render_template('forms/login.html', form=form)
    except TemplateNotFound:
        abort(404)

# Matte finns inte


@bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        if do_register(form.data['username'], form.data['password'], form.data['email']):
            flash("Registered successfully. You may now login")
            return redirect(url_for('useractions.login'))
        else:
            flash("Username already taken!")
    try:
        return render_template('forms/register.html', form=form)
    except TemplateNotFound:
        abort(404)


@bp.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('generic.serve_frontpage'))

scheduleapi/templates/forms/apikeys.html
{% extends "layout.html" %}

{% from "_formhelpers.html" import render_field %}

{% block title %}Manage API keys ScheduleAPI{% endblock %}

{% block content %}
<div class="container">
    <h1>API keys</h1>
    <hr>
    <div class="table-responsive">
      <table class="table table-striped table-condensed">
        <thead>
          <tr>
            <td>ID</td> <td>Pass</td><td>Hits</td><td></td>
          </tr>
        </thead>
      {% for apikey in apikeys %}
          <tr><td>{{ apikey.keyid }}</td><td>{{ apikey.keypass }}</td><td>{{ apikey.hits }}</td><td><a class="btn btn-danger btn-xs" href="{{url_for('generic.del_apikey', id=apikey.id)}}">Remove</a></td></tr>
      {% endfor %}
      </table>
    </div>
    <a href="{{url_for('generic.new_apikey')}}" class="btn btn-default">Generate new API key</a>
</div>
{% endblock %}

scheduleapi/templates/forms/login.html
{% extends "layout.html" %}

{% from "_formhelpers.html" import render_field %}

{% block title %}Login to ScheduleAPI{% endblock %}

{% block content %}
<div class="container">
    <h1>Login</h1>
    <hr>
    <form class="form-horizontal" method="POST" action="{{url_for('useractions.login')}}">
      {{ form.hidden_tag() }}

      {{ render_field(form.username) }}
      {{ render_field(form.password) }}

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <div class="checkbox">
            <label>
              {{ form.remember_me() }}{{ form.remember_me.label }}
            </label>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Login</button>
        </div>
      </div>
    </form>
</div>
{% endblock %}

scheduleapi/templates/forms/register.html
{% extends "layout.html" %}

{% from "_formhelpers.html" import render_field %}

{% block title %}Register to ScheduleAPI{% endblock %}

{% block content %}
<div class="container">
    <h1>Register</h1>
    <hr>
    <form class="form-horizontal" method="POST" action="{{url_for('useractions.register')}}">
      {{ form.hidden_tag() }}

      {{ render_field(form.username) }}
      {{ render_field(form.password) }}
      {{ render_field(form.pwd_confirm) }}
      {{ render_field(form.email) }}

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Register</button>
        </div>
      </div>
    </form>
</div>
{% endblock %}

scheduleapi/templates/forms/settings.html
{% extends "layout.html" %}

{% from "_formhelpers.html" import render_field %}

{% block title %}Configure ScheduleAPI{% endblock %}

{% block content %}
<div class="container">
  <h1>Settings</h1>
  <hr>
  <a class="btn btn-lg btn-default" href="{{url_for('generic.get_apikeys')}}">Manage API keys</a>
  <hr>
  <h2 class="col-sm-offset-2">User settings</h2>
  <form class="form-horizontal" method="POST" action="{{url_for('generic.settings_yo')}}">
      {{ form.hidden_tag() }}

      {{ render_field(form.password) }}
      {{ render_field(form.pwd_confirm) }}
      {{ render_field(form.email) }}

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <button type="submit" class="btn btn-default">Save</button>
        </div>
      </div>
    </form>
</div>
{% endblock %}